In [8]:
import pandas as pd
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

import os
import warnings

warnings.filterwarnings('ignore')
os.chdir('C://Users//Administrator//Desktop//Projects')

In [4]:
d = pd.read_csv('heart.csv')
d.head(2)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   

   ca  thal  target  
0   0     1       1  
1   0     2       1

In [14]:
d.shape

(303, 14)

In [5]:
x = d.drop(['target'],axis = 1)
y = d['target']

# METHOD -1  RFE

In [ ]:
### REDUCING THE DIMENSIONS ## SELECTING THE TOP FEATURES USING COEFFICIENTS IN REGRESSIONS

lr = LogisticRegression()
rfe = RFE(lr)                       ## USES LOGISTIC REGRESSION UNDERNEATH

In [9]:
rfe.fit(x,y)                          ## FINDS FEATURES WITH LOW COEFFICIENT VALUES

RFE(estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False),
  n_features_to_select=None, step=1, verbose=0)

In [13]:
x1 =rfe.transform(x)

x1.shape

(303, 6)

In [35]:
rfe.ranking_,                                   rfe.n_features_  

(array([7, 1, 1, 5, 8, 6, 3, 4, 1, 2, 1, 1, 1]), 6)

In [ ]:
##SPLIT

In [17]:
from sklearn.model_selection import train_test_split as tts

x_tr,x_ts,y_tr,y_ts = tts(x,y,test_size = 0.2)

x1_tr,x1_ts,y_tr,y_ts = tts(x1,y,test_size =0.2)

In [ ]:
## MODEL BUILDING 

In [18]:
from sklearn.ensemble import RandomForestClassifier

rf =RandomForestClassifier(n_estimators= 251)

In [20]:
## WITH SELECTED DATA

rf.fit(x1_tr,y_tr)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=251, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [21]:
rf.score(x1_ts,y_ts)

0.7704918032786885

In [23]:
# WITH ORIGINAL DATA

rf1 =RandomForestClassifier(n_estimators= 251)

rf1.fit(x_tr,y_tr)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=251, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [25]:
rf1.score(x_ts,y_ts)

0.6721311475409836

# METHOD 2 SELECTKBEST FEATURE SELECTION/EXTRACTION

In [26]:
# Feature Extraction with Univariate Statistical Tests (Chi-squared for classification)
import pandas
import numpy
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2


In [28]:
# feature extraction
# Feature Extraction with Univariate Statistical Tests (Chi-squared for classification)

kb = SelectKBest(score_func=chi2, k=6)
kb.fit(x, y)

SelectKBest(k=6, score_func=<function chi2 at 0x0000018DB5199B70>)

In [39]:
print(kb.scores_)

[ 23.287   7.577  62.598  14.824  23.936   0.203   2.978 188.32   38.914
  72.644   9.804  66.441   5.792]


In [40]:
# summarize scores

numpy.set_printoptions(precision=3)
x1 = kb.transform(x)

In [41]:
# summarize selected features
x1

array([[  3. , 233. , 150. ,   0. ,   2.3,   0. ],
       [  2. , 250. , 187. ,   0. ,   3.5,   0. ],
       [  1. , 204. , 172. ,   0. ,   1.4,   0. ],
       ...,
       [  0. , 193. , 141. ,   0. ,   3.4,   2. ],
       [  0. , 131. , 115. ,   1. ,   1.2,   1. ],
       [  1. , 236. , 174. ,   0. ,   0. ,   1. ]])

In [43]:
rf = RandomForestClassifier(n_estimators=251)

rf.fit(x1_tr,y_tr)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=251, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [44]:
rf.score(x1_ts,y_ts)

0.7540983606557377

# SAVING MODEL

In [70]:
from sklearn.externals import joblib

joblib.dump(rf, 'rf_heartmodel.pkl') 

['rf_heartmodel.pkl']

In [74]:
import pickle

pickle.dump(rf,open(filename, 'rf_heartmodel1'))

NameError: name 'filename' is not defined

In [68]:
rf.save('rf_heartmodel.h5')

AttributeError: 'RandomForestClassifier' object has no attribute 'save'

# PCA HARD CODE AND DIRECT (DMENSIONALITY REDUCTION)

In [49]:
import numpy as np
from numpy.linalg import eig
## SCALE THE DATA BEFORE USING PCA
##   1. NORMALIZE ->  2. COVARIENCE MATRIX -> 3. EIGEN(COVMATRIX) -> 4. EIGEN VALUES/EIGEN VECTORS -> 5. PC's 

# define a matrix
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [52]:
pd.DataFrame(A)

0  1
0  1  2
1  3  4
2  5  6

In [50]:
# calculate the mean of each column
M = np.mean(A.T, axis=1)
print(M)

[3. 4.]


In [51]:
# center columns by subtracting column means
C = A - M
print(C)

[[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]


In [53]:
# calculate covariance matrix of centered matrix
V = np.cov(C.T)
print(V)

[[4. 4.]
 [4. 4.]]


In [54]:
# eigendecomposition of covariance matrix
values, vectors = eig(V)
print(vectors)
print(values)

[[ 0.707 -0.707]
 [ 0.707  0.707]]
[8. 0.]


In [55]:
# project data
P = vectors.T.dot(C.T)
print(P.T)

[[-2.828  0.   ]
 [ 0.     0.   ]
 [ 2.828  0.   ]]


#  PCA DIRECT METHOD

In [56]:
from sklearn.decomposition import PCA
# define a matrix
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [57]:
# create the PCA instance
pca = PCA(2)

In [58]:
# fit on data
pca.fit(A)


# access values and vectors
print(pca.components_)
print(pca.explained_variance_)

[[ 0.707  0.707]
 [-0.707  0.707]]
[8. 0.]


In [59]:
# transform data
B = pca.transform(A)
print(B)

[[-2.828e+00 -2.220e-16]
 [ 0.000e+00  0.000e+00]
 [ 2.828e+00  2.220e-16]]


# METHOD 4 EXTRA TREE 

In [62]:
import pandas as pd
from sklearn.ensemble import ExtraTreesClassifier 

## USES DECISION TREE CLASSIFIER AND GINI INDICES

# feature extraction
etc = ExtraTreesClassifier()
etc.fit(x, y)

ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [64]:
print(etc.feature_importances_)

[0.061 0.052 0.118 0.074 0.057 0.02  0.041 0.076 0.137 0.084 0.049 0.114
 0.116]


In [66]:
indices = np.argsort(etc.feature_importances_)[::-1]
indices+1

array([ 9,  3, 13, 12, 10,  8,  4,  1,  5,  2, 11,  7,  6], dtype=int64)